# Generated by Django 5.2.4 on 2025-09-30 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collaborators/', verbose_name='Foto')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Gestor do departamento?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do sistema')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.department', verbose_name='Departamento')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['department', 'is_active'], name='common_coll_departm_672f14_idx'), models.Index(fields=['is_manager'], name='common_coll_is_mana_58b514_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='uq_common_collaborator_email_not_null')],
            },
        ),
    ]
