# Generated by Django 5.2.4 on 2025-09-30 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Atividade Geral')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Atividade Geral',
                'verbose_name_plural': 'Atividades Gerais',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PanelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tamanho do painel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tamanho do painel',
                'verbose_name_plural': 'Tamanhos de painel',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do projeto')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Código interno')),
                ('cost_center', models.CharField(blank=True, max_length=50, verbose_name='Centro de custo')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('is_open', models.BooleanField(default=True, verbose_name='Aberto?')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epe_workdays', related_query_name='epe_workday', to='common.collaborator', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ('-date', 'collaborator__name'),
                'unique_together': {('collaborator', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=120, verbose_name='Nome do painel')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epe_activities', related_query_name='epe_activity', to='common.collaborator', verbose_name='Colaborador')),
                ('general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='epe.generalactivity', verbose_name='Atividade Geral')),
                ('panel_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='epe.panelsize', verbose_name='Tamanho do painel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epe.project', verbose_name='Projeto')),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='epe.workday', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='epe.activity', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Sessão de atividade',
                'verbose_name_plural': 'Sessões de atividade',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['activity', 'started_at'], name='epe_activit_activit_0fa534_idx'), models.Index(fields=['ended_at'], name='epe_activit_ended_a_4e2561_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_active', 'started_at'], name='epe_activit_is_acti_1cba3c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['collaborator', 'started_at'], name='epe_activit_collabo_f4e660_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['general', 'panel_size'], name='epe_activit_general_bd4a75_idx'),
        ),
    ]
