# Generated by Django 5.2.4 on 2025-09-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('epe', '0003_alter_workday_collaborator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epe_workdays', related_query_name='epe_workday', to='common.collaborator', verbose_name='Colaborador'),
        ),
    ]
