# Generated by Django 5.2.4 on 2025-09-30 14:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Atividade Geral')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Atividade Geral',
                'verbose_name_plural': 'Atividades Gerais',
                'ordering': ('milestone__order', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Marco')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Marco',
                'verbose_name_plural': 'Marcos',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do projeto')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='Código interno')),
                ('cost_center', models.CharField(blank=True, max_length=50, verbose_name='Centro de custo')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_milestone', models.CharField(blank=True, max_length=80, verbose_name='Marco (ad-hoc)')),
                ('custom_general', models.CharField(blank=True, max_length=80, verbose_name='Atividade Geral (ad-hoc)')),
                ('custom_specific', models.CharField(blank=True, max_length=120, verbose_name='Atividade Específica (ad-hoc)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_activities', related_query_name='automation_activity', to='common.collaborator', verbose_name='Colaborador')),
                ('general', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.generalactivity', verbose_name='Atividade Geral')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.milestone', verbose_name='Marco')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='automation.activity', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Sessão de atividade',
                'verbose_name_plural': 'Sessões de atividade',
            },
        ),
        migrations.AddField(
            model_name='generalactivity',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generals', to='automation.milestone', verbose_name='Marco'),
        ),
        migrations.CreateModel(
            name='SpecificActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Atividade Específica')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifics', to='automation.generalactivity', verbose_name='Atividade Geral')),
            ],
            options={
                'verbose_name': 'Atividade Específica',
                'verbose_name_plural': 'Atividades Específicas',
                'ordering': ('general__milestone__order', 'general__order', 'order', 'name'),
                'unique_together': {('general', 'name')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='specific',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.specificactivity', verbose_name='Atividade Específica'),
        ),
        migrations.CreateModel(
            name='Workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('is_open', models.BooleanField(default=True, verbose_name='Aberto?')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_workdays', related_query_name='automation_workday', to='common.collaborator', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ('-date', 'collaborator__name'),
                'unique_together': {('collaborator', 'date')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='automation.workday', verbose_name='Expediente'),
        ),
        migrations.AlterUniqueTogether(
            name='generalactivity',
            unique_together={('milestone', 'name')},
        ),
    ]
