# Generated by Django 5.2.4 on 2025-09-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engobras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
    ]
