# Generated by Django 5.2.4 on 2025-11-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('engobras', '0002_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engobras_activities', related_query_name='engobras_activity', to='common.collaborator', verbose_name='Colaborador'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='general',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engobras.generalactivity', verbose_name='Atividade Geral'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engobras.milestone', verbose_name='Marco'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engobras.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='specific',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engobras.specificactivity', verbose_name='Atividade Específica'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='engobras.workday', verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='activitysession',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='engobras.activity', verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='generalactivity',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engobras_generals', to='engobras.milestone', verbose_name='Marco'),
        ),
        migrations.AlterField(
            model_name='specificactivity',
            name='general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engobras_specifics', to='engobras.generalactivity', verbose_name='Atividade Geral'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engobras_workdays', related_query_name='engobras_workday', to='common.collaborator', verbose_name='Colaborador'),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='engobras_activity',
        ),
        migrations.AlterModelTable(
            name='activitysession',
            table='engobras_activity_session',
        ),
        migrations.AlterModelTable(
            name='generalactivity',
            table='engobras_general_activity',
        ),
        migrations.AlterModelTable(
            name='milestone',
            table='engobras_milestone',
        ),
        migrations.AlterModelTable(
            name='project',
            table='engobras_project',
        ),
        migrations.AlterModelTable(
            name='specificactivity',
            table='engobras_specific_activity',
        ),
        migrations.AlterModelTable(
            name='workday',
            table='engobras_workday',
        ),
    ]
